From mysql
    ENV LC_ALL=C.UTF-8
    ENV character-set-server utf8
    ENV collation-server utf8_general_ci
    ENV default-character-set utf8
    ENV default-collation utf8-general_ci
    ENV MYSQL_DATABASE springdev
    ENV MYSQL_ROOT_PASSWORD 12345
    EXPOSE 3306